#!/usr/bin/env ruby
# frozen_string_literal: true

require "bootsnap"
Bootsnap.setup(cache_dir: "tmp/cache")

require_relative "../lib/faas_supervisor"

Sync { FaasSupervisor::Application.instance.run }
